
default: &default
  adapter: postgresql
  encoding: unicode
  
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: app_clone_development

  
test:
  <<: *default
  database: app_clone_test


production:
  <<: *default
  database: app_clone_production
  username: app_clone
  password: <%= ENV['APP_CLONE_DATABASE_PASSWORD'] %>
